apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elastic-agent
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: elastic-agent
  template:
    metadata:
      labels:
        app: elastic-agent
    spec:
      serviceAccountName: elastic-agent
      containers:
      - name: elastic-agent
        image: docker.elastic.co/beats/elastic-agent:8.15.0
        env:
          - name: FLEET_ENROLLMENT_TOKEN
            valueFrom:
              secretKeyRef:
                name: elastic-credentials
                key: api_key
          - name: FLEET_URL
            value: "https://cls-elastic-f5d375.fleet.us-central1.gcp.cloud.es.io:443"
          - name: KIBANA_FLEET_SETUP
            value: "1"
          - name: ELASTIC_AGENT_LOG_LEVEL
            value: "info"
        volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
